export const portalMockData = {
  organization: {
    name: "North Coast Trading",
    legalName: "North Coast Trading Ltd.",
    clientId: "GV-PORTAL-001",
    segment: "Treasury operations",
    domicile: "Canada",
    status: "Active",
    onboardingStatus: "In review",
  },
  profile: {
    name: "Morgan Lee",
    role: "Treasury Operations Lead",
    email: "morgan.lee@northcoast.example",
    phone: "+1 416 555 0199",
    timezone: "America/Toronto",
  },
  metrics: [
    {
      label: "Available balance",
      value: "USD 4.28M",
      detail: "Across four operating and settlement accounts",
    },
    {
      label: "Accounts in scope",
      value: "4",
      detail: "USD, EUR, GBP, and CAD balances are visible",
    },
    {
      label: "Items awaiting action",
      value: "3",
      detail: "Approvals and onboarding tasks pending review",
    },
    {
      label: "Operational status",
      value: "Normal",
      detail: "No critical exceptions are flagged in this shell",
    },
  ],
  balances: [
    {
      currency: "USD",
      available: "$2,480,000",
      reserved: "$120,000",
      detail: "Primary operating balance",
    },
    {
      currency: "EUR",
      available: "EUR 980,000",
      reserved: "EUR 42,000",
      detail: "Cross-border collections",
    },
    {
      currency: "GBP",
      available: "GBP 410,000",
      reserved: "GBP 18,500",
      detail: "UK settlement account",
    },
  ],
  accounts: [
    {
      id: "acct_usd_operating",
      name: "USD Operating Account",
      currency: "USD",
      available: "$2,480,000",
      reserved: "$120,000",
      purpose: "Domestic disbursements",
      region: "North America",
      status: "Active",
    },
    {
      id: "acct_eur_collection",
      name: "EUR Collection Account",
      currency: "EUR",
      available: "EUR 980,000",
      reserved: "EUR 42,000",
      purpose: "European receivables",
      region: "Europe",
      status: "Active",
    },
    {
      id: "acct_gbp_settlement",
      name: "GBP Settlement Account",
      currency: "GBP",
      available: "GBP 410,000",
      reserved: "GBP 18,500",
      purpose: "Local settlement",
      region: "United Kingdom",
      status: "Monitoring",
    },
    {
      id: "acct_cad_onboarding",
      name: "CAD Reserve Account",
      currency: "CAD",
      available: "CAD 620,000",
      reserved: "CAD 0",
      purpose: "Onboarding reserve",
      region: "Canada",
      status: "In review",
    },
  ],
  activity: [
    {
      id: "PAY-2026-0519-001",
      type: "Outgoing payment",
      counterparty: "Supplier settlement",
      amount: "$128,400.00",
      currency: "USD",
      rail: "Domestic transfer",
      status: "Pending approval",
      updatedAt: "2 hours ago",
    },
    {
      id: "PAY-2026-0519-002",
      type: "Incoming collection",
      counterparty: "Marketplace receipts",
      amount: "EUR 74,210.00",
      currency: "EUR",
      rail: "Regional collection",
      status: "Completed",
      updatedAt: "5 hours ago",
    },
    {
      id: "PAY-2026-0518-014",
      type: "FX funding",
      counterparty: "Treasury conversion window",
      amount: "GBP 62,000.00",
      currency: "GBP",
      rail: "Internal treasury workflow",
      status: "Processing",
      updatedAt: "Yesterday",
    },
    {
      id: "PAY-2026-0518-011",
      type: "Outgoing payment",
      counterparty: "Contractor payout batch",
      amount: "CAD 48,500.00",
      currency: "CAD",
      rail: "Domestic transfer",
      status: "Completed",
      updatedAt: "Yesterday",
    },
    {
      id: "PAY-2026-0517-009",
      type: "Account funding",
      counterparty: "Liquidity top-up",
      amount: "$300,000.00",
      currency: "USD",
      rail: "Treasury movement",
      status: "Completed",
      updatedAt: "2 days ago",
    },
  ],
  notifications: [
    {
      id: "note_1",
      title: "Additional entity review underway",
      message: "Granville is reviewing submitted formation documents for your secondary operating entity.",
      time: "Today",
      status: "In review",
      read: false,
    },
    {
      id: "note_2",
      title: "Approval matrix required",
      message: "Add final approvers before operational release can be marked production ready.",
      time: "4 hours ago",
      status: "Pending",
      read: false,
    },
    {
      id: "note_3",
      title: "Settlement account visible",
      message: "Your GBP settlement account is now available in the customer portal shell.",
      time: "Yesterday",
      status: "Completed",
      read: true,
    },
  ],
  onboardingChecklist: [
    {
      id: "step_1",
      title: "Primary entity approved",
      description: "Initial due diligence review for the main legal entity is complete.",
      status: "Completed",
    },
    {
      id: "step_2",
      title: "Additional signatory verification",
      description: "Two beneficial owner attestations remain under review.",
      status: "In progress",
    },
    {
      id: "step_3",
      title: "Approval policy configuration",
      description: "Define internal payment approvers before the release checklist closes.",
      status: "Pending",
    },
  ],
  settings: {
    displayName: "Morgan Lee",
    title: "Treasury Operations Lead",
    email: "morgan.lee@northcoast.example",
    phone: "+1 416 555 0199",
    timezone: "America/Toronto",
    reportingPreference: "Monthly operational summary",
    alertPreference: "Daily settlement digest",
  },
  contacts: [
    {
      role: "Granville relationship manager",
      name: "Client coverage team",
      detail: "Provisioned during onboarding",
    },
    {
      role: "Operational escalation",
      name: "Payments operations desk",
      detail: "Used for launch-day and release issues",
    },
    {
      role: "Internal administrator",
      name: "Morgan Lee",
      detail: "Primary approver and reporting owner",
    },
  ],
};
